server:
  port: 8364

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3302/missiondb?serverTimezone=UTC&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1111
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
#   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#   database: mysql
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  header: Autorization

  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400