server:
  port: 8364

application:
  title: mission-family-api
  version: 1.0.0-SNAPSHOT


spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3302/missiondb?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111
  banner:
    location: config/banner.txt
  config:
    import: "optional:file:./local.yml"

logging:
  call:
    multiline: true
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

  file:
    path: ./logs
    name: standard.log
  config: classpath:logback-spring-${spring.profiles.active}.xml

mission:
  logging:
    strategy: MODE_GLOBAL