spring:

  main:
    lazy-initialization: true
  profiles:
    active: local


#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  jpa:
    generate-ddl: true

    hibernate:
      ddl-auto: create
#    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.H2Dialect
#   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#   database: mysql

